buradan ulaşılacak global olarak exception handler olmadığı için try/catch kullanıyoruz.